---
title: "Prototipo di consultazione e visualizzazione del SIM"
subtitle: "Fonte Conto Annuale - Perimetro MPA"
output:
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

knitr::opts_knit$set(
  root.dir = "/Users/RominaAir/Desktop/git_mipa/Monitoraggio-PNRR"
)

setwd("/Users/RominaAir/Desktop/git_mipa/Monitoraggio-PNRR")

source("03_Scripts/00_config.R")
source("03_Scripts/00_sim_helpers.R")

library(dplyr)
library(ggplot2)
library(plotly)
library(DT)
library(googledrive)

if (exists("SIM_DRIVE_EMAIL")) {
  googledrive::drive_auth(
    email = SIM_DRIVE_EMAIL,
    scopes = "https://www.googleapis.com/auth/drive"
  )
} else {
  googledrive::drive_auth(
    scopes = "https://www.googleapis.com/auth/drive"
  )
}
```

```{r dati}
processed_ca_dir <- sim_drive_ls_path(
  file.path(DRIVE_DIR_PROCESSED, "Conto_annuale"),
  create = FALSE
)

file_indicatori_long <- googledrive::drive_ls(processed_ca_dir) %>%
  dplyr::filter(
    stringr::str_detect(
      name,
      stringr::regex("^indicatori_SIM_CA_long_multianno_.*\\.rds$", ignore_case = TRUE)
    )
  ) %>%
  dplyr::arrange(dplyr::desc(name)) %>%
  dplyr::slice(1)

if (nrow(file_indicatori_long) == 0) {
  stop("Nessun file indicatori_SIM_CA_long_multianno_*.rds trovato in Processed/Conto_annuale.")
}

local_indicatori_long <- sim_drive_download_to_temp(
  file_indicatori_long,
  local_name = file_indicatori_long$name[1],
  overwrite = TRUE
)

indicatori_long <- readRDS(local_indicatori_long)
unlink(local_indicatori_long)

message("Indicatori long CA letti da Drive: ", file_indicatori_long$name[1])

output_ca_dir <- sim_drive_ls_path(
  file.path(DRIVE_DIR_OUTPUT, "Conto_annuale"),
  create = FALSE
)

file_overview <- googledrive::drive_ls(output_ca_dir) %>%
  dplyr::filter(
    stringr::str_detect(
      name,
      stringr::regex("^sim_CA_overview_multianno_.*\\.csv$", ignore_case = TRUE)
    )
  ) %>%
  dplyr::arrange(dplyr::desc(name)) %>%
  dplyr::slice(1)

if (nrow(file_overview) == 0) {
  stop("Nessun file sim_CA_overview_multianno_*.csv trovato in Output/Conto_annuale.")
}

local_overview <- sim_drive_download_to_temp(
  file_overview,
  local_name = file_overview$name[1],
  overwrite = TRUE
)

overview <- readr::read_csv(local_overview, show_col_types = FALSE)

unlink(local_overview)

message("Overview CA letta da Drive: ", file_overview$name[1])
```


# Indicatori disponibili

```{r tabella-indicatori}
DT::datatable(
  overview,
  options = list(pageLength = 20, scrollX = TRUE)
)
```

# Andamento sintetico multianno

```{r grafico-overview}
overview_plot <- overview %>%
  filter(indicatore_id %in% c("PERSONALE_TOT", "ASSUN_TOT", "CESS_TOT", "TURNOVER_PCT", "CRESCITA_PCT"))

g <- ggplot(overview_plot, aes(x = anno, y = valore_medio, group = indicatore_id)) +
  geom_line() +
  geom_point() +
  facet_wrap(~indicatore_id, scales = "free_y") +
  labs(x = "Anno", y = "Valore medio", title = "Indicatori medi per PA - Conto Annuale") +
  theme_minimal()

plotly::ggplotly(g)
```

# Dataset indicatori in formato long

```{r tabella-long}
DT::datatable(
  indicatori_long,
  options = list(pageLength = 20, scrollX = TRUE)
)
```
